version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energie_vin
    healthcheck:
      test: psql -U postgres -c "select 1"
      interval: 2s
      retries: 10
      timeout: 1s
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external: true
